// models/task.dart
import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'task.g.dart'; // Generated file for Hive

@HiveType(typeId: 0)
class Task extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  String title;
  
  @HiveField(2)
  String? description;
  
  @HiveField(3)
  DateTime? dueDate;
  
  @HiveField(4)
  bool isCompleted;
  
  @HiveField(5)
  DateTime createdAt;
  
  @HiveField(6)
  DateTime updatedAt;
  
  @HiveField(7)
  List<String> tags;
  
  @HiveField(8)
  int? priority; // 1-3 (high, medium, low)
  
  Task({
    String? id,
    required this.title,
    this.description,
    this.dueDate,
    this.isCompleted = false,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<String>? tags,
    this.priority,
  }) : 
    this.id = id ?? const Uuid().v4(),
    this.createdAt = createdAt ?? DateTime.now(),
    this.updatedAt = updatedAt ?? DateTime.now(),
    this.tags = tags ?? [];
  
  // Create a Task from a map (for Firestore)
  factory Task.fromMap(Map<String, dynamic> map) {
    return Task(
      id: map['id'],
      title: map['title'],
      description: map['description'],
      dueDate: map['dueDate'] != null ? DateTime.parse(map['dueDate']) : null,
      isCompleted: map['isCompleted'] ?? false,
      createdAt: DateTime.parse(map['createdAt']),
      updatedAt: DateTime.parse(map['updatedAt']),
      tags: List<String>.from(map['tags'] ?? []),
      priority: map['priority'],
    );
  }
  
  // Convert Task to a map (for Firestore)
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'dueDate': dueDate?.toIso8601String(),
      'isCompleted': isCompleted,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'tags': tags,
      'priority': priority,
    };
  }
  
  // Create a copy of a Task with updated fields
  Task copyWith({
    String? title,
    String? description,
    DateTime? dueDate,
    bool? isCompleted,
    List<String>? tags,
    int? priority,
  }) {
    return Task(
      id: this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      isCompleted: isCompleted ?? this.isCompleted,
      createdAt: this.createdAt,
      updatedAt: DateTime.now(),
      tags: tags ?? List.from(this.tags),
      priority: priority ?? this.priority,
    );
  }
}

@HiveType(typeId: 1)
class PendingCommand extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String commandType; // 'add', 'update', 'delete', 'complete'
  
  @HiveField(2)
  final Map<String, dynamic> payload;
  
  @HiveField(3)
  final DateTime timestamp;
  
  PendingCommand({
    String? id,
    required this.commandType,
    required this.payload,
    DateTime? timestamp,
  }) : 
    this.id = id ?? const Uuid().v4(),
    this.timestamp = timestamp ?? DateTime.now();
    
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'commandType': commandType,
      'payload': payload,
      'timestamp': timestamp.toIso8601String(),
    };
  }
  
  factory PendingCommand.fromMap(Map<String, dynamic> map) {
    return PendingCommand(
      id: map['id'],
      commandType: map['commandType'],
      payload: Map<String, dynamic>.from(map['payload']),
      timestamp: DateTime.parse(map['timestamp']),
    );
  }
}

// This file would be generated by build_runner
// For the real implementation you'd run:
// flutter pub run build_runner build
// part 'task.g.dart'